### ISSUE TITLE
cannot change colorstyle

### ISSUE THREAD

**Issue by kokoko3k** [Alexander-r/qtvkbd#2]
In the popup menu, i just see "standart" selecting it or not does not change a thing.
I even tried to strace -f it, but there seems to be no references to the color styles css.

**Comment by alexbovet** [comment]
Hi, yes it would be nice to be able to customize the colors. For me the keys are light-blue and the letters are written in white. This combination makes it impossible to distinguish the keys.
Thanks for the work!

**Comment by Alexander-r** [comment]
Currently there are no alternative color styles available.
The "standart" one is the default style. It is used as fallback style and is stored in application resources.

You can add more styles manually. In 0.8.1 application looked for additional styles in ~/.local/share/qtvkbd/qtvkbdcolors directory. But there was a bug and the directory was not scanned. This bug should be fixed in e8c9a1b38262af8734c02fbece469db9ec22626c commit.
As of that commit application loads additional color styles from ~/.local/share/qtvkbd  /usr/local/share/qtvkbd/ and /usr/share/qtvkbd/ . It looks for css files and adds them to selection list if any are present.
https://github.com/Alexander-r/qtvkbd/blob/master/src/standart.xml can be used as an example for creating new styles. You can edit it and copy to ~/.local/share/qtvkbd . Just don’t forget to rename the file before using (color styles names in menu are based on file name).

I will try to add some more styles in the future if I have time. If anyone wants to contribute additional styles then I can add them in addition to default.

Also additional keyboard layouts can be made based on https://github.com/Alexander-r/qtvkbd/blob/master/src/standart.xml . Currently there is no option to select them. I will add it in near future.

**Comment by kokoko3k** [comment]
Oh, nice, i did not try to make any new "theme", standart is fine.
I imported css color styles from KDE/kvkbd and they works good.
For me this is enough, so i close this one, thanks!

**Comment by alexbovet** [comment]
will try! thanks!
